-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 17:13:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema piardb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema piardb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `piardb` DEFAULT CHARACTER SET utf8 ;
USE `piardb` ;

-- -----------------------------------------------------
-- Table `piardb`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`profiles` (
  `idprofile` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprofile`),
  UNIQUE INDEX `idprofiles_UNIQUE` (`idprofile` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`company_units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`company_units` (
  `idcompany_unit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcompany_unit`),
  UNIQUE INDEX `idcompany_unit_UNIQUE` (`idcompany_unit` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`departments` (
  `iddepartment` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `idcompany_unit` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iddepartment`),
  UNIQUE INDEX `iddepartments_UNIQUE` (`iddepartment` ASC),
  INDEX `fk_departments_company_units1_idx` (`idcompany_unit` ASC),
  CONSTRAINT `fk_departments_company_units1`
    FOREIGN KEY (`idcompany_unit`)
    REFERENCES `piardb`.`company_units` (`idcompany_unit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`users` (
  `iduser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpf` BIGINT(11) UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `fullname` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `current_score` INT UNSIGNED NOT NULL,
  `total_score` INT UNSIGNED NOT NULL,
  `idprofile` INT UNSIGNED NOT NULL,
  `iddepartment` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `idusers_UNIQUE` (`iduser` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_users_profiles_idx` (`idprofile` ASC),
  INDEX `fk_users_departments1_idx` (`iddepartment` ASC),
  CONSTRAINT `fk_users_profiles`
    FOREIGN KEY (`idprofile`)
    REFERENCES `piardb`.`profiles` (`idprofile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_departments1`
    FOREIGN KEY (`iddepartment`)
    REFERENCES `piardb`.`departments` (`iddepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`ideas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`ideas` (
  `ididea` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` TINYINT UNSIGNED NOT NULL,
  `register_date` DATE NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `user_identification` TINYINT(1) UNSIGNED NOT NULL,
  `likes` INT UNSIGNED NOT NULL,
  `comments` INT UNSIGNED NOT NULL,
  `idapprover` INT UNSIGNED NOT NULL,
  `expected_results` VARCHAR(80) NULL,
  `observation_approval` VARCHAR(200) NULL,
  `iddepartment` INT UNSIGNED NOT NULL,
  `idauthor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ididea`),
  UNIQUE INDEX `ididea_UNIQUE` (`ididea` ASC),
  INDEX `fk_ideas_departments1_idx` (`iddepartment` ASC),
  INDEX `fk_ideas_users1_idx` (`idauthor` ASC),
  CONSTRAINT `fk_ideas_departments1`
    FOREIGN KEY (`iddepartment`)
    REFERENCES `piardb`.`departments` (`iddepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ideas_users1`
    FOREIGN KEY (`idauthor`)
    REFERENCES `piardb`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`rewards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`rewards` (
  `idreward` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `score` SMALLINT UNSIGNED NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idreward`),
  UNIQUE INDEX `idreward_UNIQUE` (`idreward` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`likes` (
  `idlike` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` TINYINT(1) UNSIGNED NULL,
  `iduser` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idlike`),
  UNIQUE INDEX `idlike_UNIQUE` (`idlike` ASC),
  INDEX `fk_likes_users1_idx` (`iduser` ASC),
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `piardb`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`comments` (
  `idcomment` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `likes` INT UNSIGNED NOT NULL,
  `suggestion` VARCHAR(200) NULL,
  `iduser` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcomment`),
  UNIQUE INDEX `idcomment_UNIQUE` (`idcomment` ASC),
  INDEX `fk_comments_users1_idx` (`iduser` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `piardb`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`rewards_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`rewards_has_users` (
  `idreward` INT UNSIGNED NOT NULL,
  `iduser` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idreward`, `iduser`),
  INDEX `fk_rewards_has_users_users1_idx` (`iduser` ASC),
  INDEX `fk_rewards_has_users_rewards1_idx` (`idreward` ASC),
  CONSTRAINT `fk_rewards_has_users_rewards1`
    FOREIGN KEY (`idreward`)
    REFERENCES `piardb`.`rewards` (`idreward`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rewards_has_users_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `piardb`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`improvements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`improvements` (
  `ididea` INT UNSIGNED NOT NULL,
  `iduser` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ididea`, `iduser`),
  INDEX `fk_ideas_has_users_users1_idx` (`iduser` ASC),
  INDEX `fk_ideas_has_users_ideas1_idx` (`ididea` ASC),
  CONSTRAINT `fk_ideas_has_users_ideas1`
    FOREIGN KEY (`ididea`)
    REFERENCES `piardb`.`ideas` (`ididea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ideas_has_users_users1`
    FOREIGN KEY (`iduser`)
    REFERENCES `piardb`.`users` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`ideas_has_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`ideas_has_likes` (
  `ididea` INT UNSIGNED NOT NULL,
  `idlike` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ididea`, `idlike`),
  INDEX `fk_ideas_has_likes_likes1_idx` (`idlike` ASC),
  INDEX `fk_ideas_has_likes_ideas1_idx` (`ididea` ASC),
  CONSTRAINT `fk_ideas_has_likes_ideas1`
    FOREIGN KEY (`ididea`)
    REFERENCES `piardb`.`ideas` (`ididea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ideas_has_likes_likes1`
    FOREIGN KEY (`idlike`)
    REFERENCES `piardb`.`likes` (`idlike`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`ideas_has_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`ideas_has_comments` (
  `ididea` INT UNSIGNED NOT NULL,
  `idcomment` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ididea`, `idcomment`),
  INDEX `fk_ideas_has_comments_comments1_idx` (`idcomment` ASC),
  INDEX `fk_ideas_has_comments_ideas1_idx` (`ididea` ASC),
  CONSTRAINT `fk_ideas_has_comments_ideas1`
    FOREIGN KEY (`ididea`)
    REFERENCES `piardb`.`ideas` (`ididea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ideas_has_comments_comments1`
    FOREIGN KEY (`idcomment`)
    REFERENCES `piardb`.`comments` (`idcomment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piardb`.`comments_has_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piardb`.`comments_has_likes` (
  `idcomment` INT UNSIGNED NOT NULL,
  `idlike` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcomment`, `idlike`),
  INDEX `fk_comments_has_likes_likes1_idx` (`idlike` ASC),
  INDEX `fk_comments_has_likes_comments1_idx` (`idcomment` ASC),
  CONSTRAINT `fk_comments_has_likes_comments1`
    FOREIGN KEY (`idcomment`)
    REFERENCES `piardb`.`comments` (`idcomment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_has_likes_likes1`
    FOREIGN KEY (`idlike`)
    REFERENCES `piardb`.`likes` (`idlike`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
